const PartsOptions = [
  {
    product: 'PERFORMANCE 2S LS HYBRID PATIO DOOR FRAME',
    parts: [
      {
        id: 1,
        desc: 'A3011-Left SUPPORT BLOCK XO-OX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 2,
        desc: 'A3011-Left SUPPORT BLOCK XOX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 3,
        desc: 'A3011-Left SUPPORT BLOCK OXXO 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 4,
        desc: 'A3011-Right SUPPORT BLOCK XO-OX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 5,
        desc: 'A3011-Right SUPPORT BLOCK XOX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 6,
        desc: 'A3011-Right SUPPORT BLOCK OXXO 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 7,
        desc: 'A3005 HEAD GROOVE COVER XO-OX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 8,
        desc: 'A3005 HEAD GROOVE COVER XOX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 9,
        desc: 'A3005 HEAD GROOVE COVER OXXO 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 10,
        desc: 'A3005 JAMB GROOVE COVER XO-OX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 11,
        desc: 'A3005 JAMB GROOVE COVER XOX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 12,
        desc: 'A3005 JAMB GROOVE COVER OX-O 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 13,
        desc: 'A3005 JAMB GROOVE COVER OXXO 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
    ],
  },

  {
    product: 'PERFORMANCE 2S LS HYBRID PATIO DOOR SASH',
    parts: [
      {
        id: 1,
        desc: 'A268 HORIZONTAL SASH CLAD XO-OX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 2,
        desc: 'A268 HORIZONTAL SASH CLAD XOX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 3,
        desc: 'A268 HORIZONTAL SASH CLAD OX-O 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 4,
        desc: 'A268 HORIZONTAL SASH CLAD OXXO 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 5,
        desc: 'A269 VERTICAL SASH CLAD XO-OX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 6,
        desc: 'A269 VERTICAL SASH CLAD XOX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 7,
        desc: 'A269 VERTICAL SASH CLAD OX-O 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 8,
        desc: 'A269 VERTICAL SASH CLAD OXXO 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 9,
        desc: 'A279 FIXED SNAP-ON XO-OX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 10,
        desc: 'A279 FIXED SNAP-ON XOX 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 11,
        desc: 'A279 FIXED SNAP-ON OX-O 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 12,
        desc: 'A279 FIXED SNAP-ON OXXO 2S LS HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
    ],
  },

  {
    product: 'PERFORMANCE 2S LS HYBRID PATIO DOOR XO-OX',
    piece: 'FULL FRAME',
    parts: [
      {
        id: 1,
        desc: 'A3011-Left SUPPORT BLOCK XO-OX',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 2,
        desc: 'A3005 HEAD GROOVE COVER XO-OX',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 3,
        desc: 'A3005 JAMB GROOVE COVER XO-OX',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
    ],
  },
  {
    product: 'PERFORMANCE 2S HYBRID PATIO DOOR FRAME',
    parts: [
      {
        id: 1,
        desc: 'A3011-Left SUPPORT BLOCK XO-OX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 2,
        desc: 'A3011-Left SUPPORT BLOCK XOX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 3,
        desc: 'A3011-Left SUPPORT BLOCK OXXO 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 4,
        desc: 'A3011-Right SUPPORT BLOCK XO-OX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 5,
        desc: 'A3011-Right SUPPORT BLOCK XOX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 6,
        desc: 'A3011-Right SUPPORT BLOCK OXXO 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 7,
        desc: 'A3005 HEAD GROOVE COVER XO-OX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 8,
        desc: 'A3005 HEAD GROOVE COVER XOX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 9,
        desc: 'A3005 HEAD GROOVE COVER OXXO 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 10,
        desc: 'A3005 JAMB GROOVE COVER XO-OX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 11,
        desc: 'A3005 JAMB GROOVE COVER XOX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 12,
        desc: 'A3005 JAMB GROOVE COVER OX-O 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 13,
        desc: 'A3005 JAMB GROOVE COVER OXXO 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
    ],
  },
  {
    product: 'PERFORMANCE 2S HYBRID PATIO DOOR SASH',
    parts: [
      {
        id: 1,
        desc: 'A268 HORIZONTAL SASH CLAD XO-OX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 2,
        desc: 'A268 HORIZONTAL SASH CLAD XOX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 3,
        desc: 'A268 HORIZONTAL SASH CLAD OX-O 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 4,
        desc: 'A268 HORIZONTAL SASH CLAD OXXO 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 5,
        desc: 'A269 VERTICAL SASH CLAD XO-OX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 6,
        desc: 'A269 VERTICAL SASH CLAD XOX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 7,
        desc: 'A269 VERTICAL SASH CLAD OX-O 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 8,
        desc: 'A269 VERTICAL SASH CLAD OXXO 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 9,
        desc: 'A279 FIXED SNAP-ON XO-OX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 10,
        desc: 'A279 FIXED SNAP-ON XOX 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 11,
        desc: 'A279 FIXED SNAP-ON OX-O 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 12,
        desc: 'A279 FIXED SNAP-ON OXXO 2S HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
    ],
  },

  {
    product: 'PERFORMANCE 2S LS PVC PATIO DOOR FRAME',
    parts: [
      {
        id: 1,
        desc: 'A3011-Left SUPPORT BLOCK XO-OX 2S LS PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 2,
        desc: 'A3011-Left SUPPORT BLOCK XOX 2S LS PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 3,
        desc: 'A3011-Left SUPPORT BLOCK OXXO 2S LS PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 4,
        desc: 'A3011-Right SUPPORT BLOCK XO-OX 2S LS PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 5,
        desc: 'A3011-Right SUPPORT BLOCK XOX 2S LS PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 6,
        desc: 'A3011-Right SUPPORT BLOCK OXXO 2S LS PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
    ],
  },

  {
    product: 'PERFORMANCE 2S PVC PATIO DOOR FRAME',
    parts: [
      {
        id: 1,
        desc: 'A3011-Left SUPPORT BLOCK XO-OX 2S PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 2,
        desc: 'A3011-Left SUPPORT BLOCK XOX 2S PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 3,
        desc: 'A3011-Left SUPPORT BLOCK OXXO 2S PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 4,
        desc: 'A3011-Right SUPPORT BLOCK XO-OX 2S PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 5,
        desc: 'A3011-Right SUPPORT BLOCK XOX 2S PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 6,
        desc: 'A3011-Right SUPPORT BLOCK OXXO 2S PVC',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
    ],
  },
  {
    product: 'PERFORMANCE HYBRID PATIO DOOR FRAME',
    parts: [
      {
        id: 1,
        desc: 'A3005 HEAD GROOVE COVER XO-OX HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 2,
        desc: 'A3005 HEAD GROOVE COVER XOX HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 3,
        desc: 'A3005 HEAD GROOVE COVER OXXO HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 4,
        desc: 'A3005 HEAD GROOVE COVER XO-OX  WITH MP HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 5,
        desc: 'A3005 HEAD GROOVE COVER XOX WITH MP HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 6,
        desc: 'A3005 HEAD GROOVE COVER OXXO WITH MP HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
    ],
  },
  {
    product: 'PERFORMANCE HYBRID PATIO DOOR SASH',
    parts: [
      {
        id: 1,
        desc: 'A268 HORIZONTAL SASH CLAD XO-OX HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 2,
        desc: 'A268 HORIZONTAL SASH CLAD XOX HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 3,
        desc: 'A268 HORIZONTAL SASH CLAD OXXO HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 4,
        desc: 'A268 HORIZONTAL SASH CLAD XO-OX  WITH MP HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 5,
        desc: 'A268 HORIZONTAL SASH CLAD XOX WITH MP HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 6,
        desc: 'A268 HORIZONTAL SASH CLAD OXXO WITH MP HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },

      {
        id: 7,
        desc: 'A269 VERTICAL SASH CLAD XO-OX HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 8,
        desc: 'A269 VERTICAL SASH CLAD XOX HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 9,
        desc: 'A269 VERTICAL SASH CLAD OXXO HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 10,
        desc: 'A269 VERTICAL SASH CLAD XO-OX  WITH MP HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 11,
        desc: 'A269 VERTICAL SASH CLAD XOX WITH MP HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
      {
        id: 12,
        desc: 'A269 VERTICAL SASH CLAD OXXO WITH MP HYB',
        wideEnable: true,
        heightEnable: true,
        handleHeightEnable: true,
      },
    ],
  },
]

export default PartsOptions
