const ProductsOptions = [
  {
    piece: 'FULL FRAME',
    products: [
      { id: 1, desc: 'PERFORMANCE 2S LS HYBRID PATIO DOOR XO-OX' },
      { id: 2, desc: 'PERFORMANCE 2S LS HYBRID PATIO DOOR XOX' },
      { id: 3, desc: 'PERFORMANCE 2S LS HYBRID PATIO DOOR OX-O' },
      { id: 4, desc: 'PERFORMANCE 2S LS HYBRID PATIO DOOR OXXO' },
      { id: 5, desc: 'PERFORMANCE 2S HYBRID PATIO DOOR XO-OX' },
      { id: 6, desc: 'PERFORMANCE 2S HYBRID PATIO DOOR XOX' },
      { id: 7, desc: 'PERFORMANCE 2S HYBRID PATIO DOOR OX-O' },
      { id: 8, desc: 'PERFORMANCE 2S HYBRID PATIO DOOR OXXO' },
      { id: 9, desc: 'PERFORMANCE 2S LS PVC PATIO DOOR XO-OX' },
      { id: 10, desc: 'PERFORMANCE 2S LS PVC PATIO DOOR XOX' },
      { id: 11, desc: 'PERFORMANCE 2S LS PVC PATIO DOOR OXXO' },
      { id: 12, desc: 'PERFORMANCE 2S PVC PATIO DOOR XO-OX' },
      { id: 13, desc: 'PERFORMANCE 2S PVC PATIO DOOR XOX' },
      { id: 14, desc: 'PERFORMANCE 2S PVC PATIO DOOR OXXO' },
      { id: 15, desc: 'PERFORMANCE HYBRID PATIO DOOR XO-OX' },
      { id: 16, desc: 'PERFORMANCE HYBRID PATIO DOOR XOX' },
      { id: 17, desc: 'PERFORMANCE HYBRID PATIO DOOR OXXO' },
      { id: 18, desc: 'PERFORMANCE HYBRID PATIO DOOR XO-OX  WITH MP' },
      { id: 19, desc: 'PERFORMANCE HYBRID PATIO DOOR XOX WITH MP' },
      { id: 20, desc: 'PERFORMANCE HYBRID PATIO DOOR OXXO WITH MP' },
    ],
  },
  {
    piece: 'FULL SASH',
    products: [
      { id: 1, desc: 'PERFORMANCE 2S LS HYBRID PATIO DOOR XO-OX' },
      { id: 2, desc: 'PERFORMANCE 2S LS HYBRID PATIO DOOR XOX' },
      { id: 3, desc: 'PERFORMANCE 2S LS HYBRID PATIO DOOR OX-O' },
      { id: 4, desc: 'PERFORMANCE 2S LS HYBRID PATIO DOOR OXXO' },
      { id: 5, desc: 'PERFORMANCE 2S HYBRID PATIO DOOR XO-OX' },
      { id: 6, desc: 'PERFORMANCE 2S HYBRID PATIO DOOR XOX' },
      { id: 7, desc: 'PERFORMANCE 2S HYBRID PATIO DOOR OX-O' },
      { id: 8, desc: 'PERFORMANCE 2S HYBRID PATIO DOOR OXXO' },
      { id: 9, desc: 'PERFORMANCE 2S LS PVC PATIO DOOR XO-OX' },
      { id: 10, desc: 'PERFORMANCE 2S LS PVC PATIO DOOR XOX' },
      { id: 11, desc: 'PERFORMANCE 2S LS PVC PATIO DOOR OXXO' },
      { id: 12, desc: 'PERFORMANCE 2S PVC PATIO DOOR XO-OX' },
      { id: 13, desc: 'PERFORMANCE 2S PVC PATIO DOOR XOX' },
      { id: 14, desc: 'PERFORMANCE 2S PVC PATIO DOOR OXXO' },
      { id: 15, desc: 'PERFORMANCE HYBRID PATIO DOOR XO-OX' },
      { id: 16, desc: 'PERFORMANCE HYBRID PATIO DOOR XOX' },
      { id: 17, desc: 'PERFORMANCE HYBRID PATIO DOOR OXXO' },
      { id: 18, desc: 'PERFORMANCE HYBRID PATIO DOOR OX-O' },
      { id: 19, desc: 'PERFORMANCE HYBRID PATIO DOOR XO-OX  WITH MP' },
      { id: 20, desc: 'PERFORMANCE HYBRID PATIO DOOR XOX WITH MP' },
      { id: 21, desc: 'PERFORMANCE HYBRID PATIO DOOR OXXO WITH MP' },
    ],
  },
  {
    piece: 'SINGLE PIECES',
    products: [
      { id: 1, desc: 'PERFORMANCE 2S LS HYBRID PATIO DOOR FRAME' },
      { id: 2, desc: 'PERFORMANCE 2S LS HYBRID PATIO DOOR SASH' },
      { id: 3, desc: 'PERFORMANCE 2S HYBRID PATIO DOOR FRAME' },
      { id: 4, desc: 'PERFORMANCE 2S HYBRID PATIO DOOR SASH' },
      { id: 5, desc: 'PERFORMANCE 2S LS PVC PATIO DOOR FRAME' },
      { id: 6, desc: 'PERFORMANCE 2S PVC PATIO DOOR FRAME' },
      { id: 7, desc: 'PERFORMANCE HYBRID PATIO DOOR FRAME' },
      { id: 8, desc: 'PERFORMANCE HYBRID PATIO DOOR SASH' },
    ],
  },
]

export default ProductsOptions
